language: python

python:
  - 2.7

#services: postgresql

env:
  - DJANGO=1.11

#before_install:
#  - export DJANGO_SETTINGS_MODULE=your_project.settings
#  - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
#  - export PIP_USE_MIRRORS=true

install:
#  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO
#  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py test

after_script:
  - fab help